/** Driver roster — CJ Permann #37 + Dylan Permann #777 (Permann Diesel / Colorado Pawn) */

export const PLAYER = {
  id: "player",
  name: "CJ Permann",
  team: "Permann Diesel Solutions",
  number: "37",
  carName: "#37 CJ Permann",
  sponsors: "Colorado Pawn & Jewelry · Permann Diesel Solutions · Hoosier",
  bio: "CJ Permann’s dirt late model — black, orange, green #37.",
  body: "#1a1a1a",
  accent: "#e85d04",
  trim: "#3d9e3a",
  stripe: "#f0b429",
  checkered: true,
  portrait: "assets/cars/player-37-pit.jpg",
  action: "assets/cars/player-37-action.jpg",
  skill: 1,
  aggression: 0.55,
};

/** Rival late models in the same class / silhouette style */
export const RIVALS = [
  {
    id: "dylan",
    name: "Dylan Permann",
    team: "Permann Diesel Solutions",
    number: "777",
    carName: "#777 Permann",
    sponsors: "Permann Diesel Solutions · UP Signs · Hoosier · 5 Star",
    bio: "Teammate in the black #777 — lime wheels, red flames, checkered wins.",
    body: "#0d0d0d",
    accent: "#e85d04",
    trim: "#7CFC00",
    stripe: "#ff2a2a",
    checkered: false,
    portrait: "assets/cars/dylan-777.jpg",
    skill: 0.97,
    aggression: 0.62,
  },
  {
    id: "dusty",
    name: "Jake “Dusty” Morales",
    team: "High Banks Hauling",
    number: "21",
    carName: "#21 High Banks",
    sponsors: "High Banks Hauling · Sunbelt Tools",
    bio: "Loves the cushion. Fast in, messy out.",
    body: "#1e3a8a",
    accent: "#ffffff",
    trim: "#60a5fa",
    stripe: "#fbbf24",
    checkered: false,
    portrait: "assets/cars/rival-21.jpg",
    skill: 0.92,
    aggression: 0.7,
  },
  {
    id: "highline",
    name: "Sarah “Highline” Brooks",
    team: "Brooks Racing",
    number: "07",
    carName: "#07 Brooks",
    sponsors: "Brooks Fabrication · Pink Ribbon Tire",
    bio: "Smooth on the bottom. Hard to pass.",
    body: "#111111",
    accent: "#ec4899",
    trim: "#f9a8d4",
    stripe: "#ffffff",
    checkered: false,
    portrait: "assets/cars/rival-07.jpg",
    skill: 0.96,
    aggression: 0.4,
  },
  {
    id: "bigtom",
    name: "Big Tom Harlan",
    team: "Harlan Farms",
    number: "99",
    carName: "#99 Harlan Farms",
    sponsors: "Harlan Farms · Diesel King",
    bio: "Throws weight around in traffic.",
    body: "#ca8a04",
    accent: "#111111",
    trim: "#fde047",
    stripe: "#ffffff",
    checkered: true,
    portrait: "assets/cars/rival-99.jpg",
    skill: 0.88,
    aggression: 0.85,
  },
  {
    id: "cushion",
    name: "Ricky “Cushion” Vance",
    team: "Vance Motorsports",
    number: "44",
    carName: "#44 Vance",
    sponsors: "Vance Exhaust · Night Owl Energy",
    bio: "Wall scrapes for free speed.",
    body: "#5b21b6",
    accent: "#c4b5fd",
    trim: "#a78bfa",
    stripe: "#f0b429",
    checkered: false,
    portrait: "assets/cars/rival-44.jpg",
    skill: 0.9,
    aggression: 0.75,
  },
  {
    id: "nina",
    name: "Nina Okonkwo",
    team: "Lagos Speed Co.",
    number: "5",
    carName: "#5 Lagos Speed",
    sponsors: "Lagos Speed · Apex Oil",
    bio: "Technical setup geek. Strong late.",
    body: "#0f766e",
    accent: "#99f6e4",
    trim: "#14b8a6",
    stripe: "#f8fafc",
    checkered: false,
    portrait: "assets/cars/rival-05.jpg",
    skill: 0.94,
    aggression: 0.45,
  },
  {
    id: "outlaw",
    name: "Colt “Outlaw” Reyes",
    team: "Reyes Racing",
    number: "13",
    carName: "#13 Outlaw",
    sponsors: "Reyes Welding · Iron Horse Bar",
    bio: "Starts deep, charges hard.",
    body: "#7f1d1d",
    accent: "#fca5a5",
    trim: "#ef4444",
    stripe: "#fbbf24",
    checkered: true,
    portrait: "assets/cars/rival-13.jpg",
    skill: 0.91,
    aggression: 0.9,
  },
  {
    id: "greta",
    name: "Greta Lindstrom",
    team: "Nordic Dirt",
    number: "88",
    carName: "#88 Nordic",
    sponsors: "Nordic Dirt · Fjord Tools",
    bio: "Patient. Waits for your mistake.",
    body: "#f8fafc",
    accent: "#1d4ed8",
    trim: "#93c5fd",
    stripe: "#ef4444",
    checkered: false,
    portrait: "assets/cars/rival-88.jpg",
    skill: 0.93,
    aggression: 0.35,
  },
  {
    id: "moose",
    name: "“Moose” Delgado",
    team: "Delgado Diesel",
    number: "62",
    carName: "#62 Delgado Diesel",
    sponsors: "Delgado Diesel · Trackside BBQ",
    bio: "Power steering and bad intentions.",
    body: "#365314",
    accent: "#a3e635",
    trim: "#84cc16",
    stripe: "#facc15",
    checkered: false,
    portrait: "assets/cars/rival-62.jpg",
    skill: 0.87,
    aggression: 0.8,
  },
];

export function getRival(id) {
  return RIVALS.find((r) => r.id === id);
}

export function defaultSelectedRivals() {
  // Dylan #777 always in the default field when available
  const preferred = ["dylan", "dusty", "highline", "bigtom", "cushion"];
  const ids = preferred.filter((id) => RIVALS.some((r) => r.id === id));
  for (const r of RIVALS) {
    if (ids.length >= 5) break;
    if (!ids.includes(r.id)) ids.push(r.id);
  }
  return ids.slice(0, 5);
}
