/**
 * Dirt track schedule — UNOH / NW Ohio circuit + Florida stops.
 * UNOH = University of Northwestern Ohio (Lima, OH).
 */

export const TRACKS = [
  {
    id: "unoh",
    name: "UNOH Racetrack",
    shortName: "UNOH",
    location: "Lima, OH",
    region: "Ohio",
    desc: "University of Northwestern Ohio campus dirt oval — home of Racers.",
    outerRx: 92,
    outerRy: 56,
    innerRx: 50,
    innerRy: 23,
    bank: 0.85,
    clay: "#c4a07a",
    sky: "#0c101c",
    // Short punchy lines — huge Impact type on black
    signs: [
      { title: "UNOH", sub: "RACETRACK", tag: "LIMA OH", bg: "#000", accent: "#FFD200" },
      { title: "UNOH", sub: "RACERS", tag: "GO RACERS", bg: "#000", accent: "#3B82F6" },
      { title: "PERMANN", sub: "DIESEL", tag: "#37  #777", bg: "#000", accent: "#22C55E" },
      { title: "COLORADO", sub: "PAWN", tag: "JEWELRY", bg: "#000", accent: "#FFD200" },
    ],
  },
  {
    id: "limaland",
    name: "Limaland Motorsports Park",
    shortName: "Limaland",
    location: "Lima, OH",
    region: "Ohio",
    desc: "High-banked 1/4-mile clay right next to UNOH country.",
    outerRx: 88,
    outerRy: 54,
    innerRx: 48,
    innerRy: 22,
    bank: 1.15,
    clay: "#b8956a",
    sky: "#0a0e18",
    signs: [
      { title: "LIMALAND", sub: "MOTORSPORTS", tag: "LIMA OH", bg: "#000", accent: "#FF6B00" },
      { title: "OHIO", sub: "DIRT", tag: "SAT NIGHT", bg: "#000", accent: "#FFD200" },
      { title: "PERMANN", sub: "DIESEL", tag: "SOLUTIONS", bg: "#000", accent: "#22C55E" },
      { title: "COLORADO", sub: "PAWN", tag: "JEWELRY", bg: "#000", accent: "#FFD200" },
    ],
  },
  {
    id: "waynesfield",
    name: "Waynesfield Raceway Park",
    shortName: "Waynesfield",
    location: "Waynesfield, OH",
    region: "Ohio",
    desc: "Tight NW Ohio bullring — technical and physical.",
    outerRx: 82,
    outerRy: 50,
    innerRx: 46,
    innerRy: 21,
    bank: 0.7,
    clay: "#c9a070",
    sky: "#0d121f",
    signs: [
      { title: "WAYNESFIELD", sub: "RACEWAY", tag: "OHIO", bg: "#000", accent: "#60A5FA" },
      { title: "UNOH", sub: "TOUR", tag: "NW OHIO", bg: "#000", accent: "#FFD200" },
      { title: "PERMANN", sub: "DIESEL", tag: "CJ #37", bg: "#000", accent: "#FF6B00" },
      { title: "COLORADO", sub: "PAWN", tag: "JEWELRY", bg: "#000", accent: "#FFD200" },
    ],
  },
  {
    id: "eldora",
    name: "Eldora Speedway",
    shortName: "Eldora",
    location: "Rossburg, OH",
    region: "Ohio",
    desc: "The Big E — legendary half-mile clay temple of dirt.",
    outerRx: 110,
    outerRy: 68,
    innerRx: 58,
    innerRy: 28,
    bank: 1.35,
    clay: "#a87848",
    sky: "#080c14",
    signs: [
      { title: "ELDORA", sub: "SPEEDWAY", tag: "ROSSBURG OH", bg: "#000", accent: "#FFD700" },
      { title: "THE BIG E", sub: "HALF MILE", tag: "WORLD FAMOUS", bg: "#000", accent: "#FF6B00" },
      { title: "PERMANN", sub: "DIESEL", tag: "#37  #777", bg: "#000", accent: "#22C55E" },
      { title: "COLORADO", sub: "PAWN", tag: "JEWELRY", bg: "#000", accent: "#FFD200" },
    ],
  },
  {
    id: "oakshade",
    name: "Oakshade Raceway",
    shortName: "Oakshade",
    location: "Wauseon, OH",
    region: "Ohio",
    desc: "NW Ohio short track heat — cushion and groove.",
    outerRx: 90,
    outerRy: 55,
    innerRx: 49,
    innerRy: 22,
    bank: 0.95,
    clay: "#bc9470",
    sky: "#0b1020",
    signs: [
      { title: "OAKSHADE", sub: "RACEWAY", tag: "WAUSEON OH", bg: "#000", accent: "#4ADE80" },
      { title: "UNOH", sub: "TOUR", tag: "OHIO DIRT", bg: "#000", accent: "#FFD200" },
      { title: "PERMANN", sub: "DIESEL", tag: "SOLUTIONS", bg: "#000", accent: "#22C55E" },
      { title: "COLORADO", sub: "PAWN", tag: "JEWELRY", bg: "#000", accent: "#FFD200" },
    ],
  },
  {
    id: "fremont",
    name: "Fremont Speedway",
    shortName: "Fremont",
    location: "Fremont, OH",
    region: "Ohio",
    desc: "The Track That Action Built — fast and famous.",
    outerRx: 94,
    outerRy: 57,
    innerRx: 51,
    innerRy: 24,
    bank: 1.05,
    clay: "#b88858",
    sky: "#0a0f1a",
    signs: [
      { title: "FREMONT", sub: "SPEEDWAY", tag: "FREMONT OH", bg: "#000", accent: "#C084FC" },
      { title: "ACTION", sub: "BUILT", tag: "OHIO DIRT", bg: "#000", accent: "#FFD200" },
      { title: "PERMANN", sub: "DIESEL", tag: "POWER", bg: "#000", accent: "#FF6B00" },
      { title: "COLORADO", sub: "PAWN", tag: "JEWELRY", bg: "#000", accent: "#FFD200" },
    ],
  },
  {
    id: "attica",
    name: "Attica Raceway Park",
    shortName: "Attica",
    location: "Attica, OH",
    region: "Ohio",
    desc: "Ohio Speedweek clay — technical entry, big exit speed.",
    outerRx: 96,
    outerRy: 58,
    innerRx: 52,
    innerRy: 24,
    bank: 1.1,
    clay: "#b08050",
    sky: "#0c1018",
    signs: [
      { title: "ATTICA", sub: "RACEWAY", tag: "ATTICA OH", bg: "#000", accent: "#FBBF24" },
      { title: "SPEEDWEEK", sub: "CLAY", tag: "OHIO", bg: "#000", accent: "#FF6B00" },
      { title: "PERMANN", sub: "DIESEL", tag: "CJ #37", bg: "#000", accent: "#22C55E" },
      { title: "COLORADO", sub: "PAWN", tag: "JEWELRY", bg: "#000", accent: "#FFD200" },
    ],
  },
  {
    id: "ocala",
    name: "Bubba Raceway Park",
    shortName: "Ocala",
    location: "Ocala, FL",
    region: "Florida",
    desc: "Ocala, Florida clay under the palms — winter warrior stop.",
    outerRx: 98,
    outerRy: 60,
    innerRx: 53,
    innerRy: 25,
    bank: 0.9,
    clay: "#d4b896",
    sky: "#0a1520",
    signs: [
      { title: "BUBBA", sub: "RACEWAY", tag: "OCALA FL", bg: "#000", accent: "#4ADE80" },
      { title: "OCALA", sub: "FLORIDA", tag: "DIRT", bg: "#000", accent: "#FFD200" },
      { title: "PERMANN", sub: "DIESEL", tag: "FLORIDA", bg: "#000", accent: "#22C55E" },
      { title: "COLORADO", sub: "PAWN", tag: "JEWELRY", bg: "#000", accent: "#FFD200" },
    ],
  },
  {
    id: "hendry",
    name: "Hendry County Speedway",
    shortName: "Hendry Co.",
    location: "Hendry County, FL",
    region: "Florida",
    desc: "South Florida dirt — hot nights, sticky clay, big slides.",
    outerRx: 86,
    outerRy: 52,
    innerRx: 47,
    innerRy: 21,
    bank: 0.75,
    clay: "#d2a878",
    sky: "#0c1820",
    signs: [
      { title: "HENDRY", sub: "COUNTY", tag: "FLORIDA", bg: "#000", accent: "#FBBF24" },
      { title: "HENDRY CO", sub: "SPEEDWAY", tag: "SOUTH FL", bg: "#000", accent: "#4ADE80" },
      { title: "PERMANN", sub: "DIESEL", tag: "#37  #777", bg: "#000", accent: "#FF6B00" },
      { title: "COLORADO", sub: "PAWN", tag: "JEWELRY", bg: "#000", accent: "#FFD200" },
    ],
  },
];

export function getTrack(id) {
  return TRACKS.find((t) => t.id === id) || TRACKS[0];
}

/** Season schedule order */
export function trackForRound(round) {
  return TRACKS[round % TRACKS.length];
}

export function allTracksList() {
  return TRACKS.map((t, i) => ({
    index: i + 1,
    id: t.id,
    name: t.name,
    location: t.location,
    region: t.region,
    desc: t.desc,
  }));
}
